apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mainlb
  namespace: three-tier
  annotations:
    ingressClassName: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    kubernetes.io/role/internal-elb: 1
spec:
  rules:
   
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:   
                  number: 3500
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port: 
                  number: 3000
      
